socialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('profile/', views.profile, name="profile"),
    path('auth/register/', views.register_view, name="register"),
    path('auth/login/', views.login_view, name="login"),
    path('auth/logout/', views.logout_view, name="logout"),
    path('create_post/', views.create_post, name="create_post"),
    path('delete_post/<int:id>', views.delete_post, name="delete_post"),
    path('showuser/<int:id>', views.showuser, name="showuser"),
    path('follow/<int:id>', views.follow, name="follow"),
    path('unfollow/<int:id>', views.unfollow, name="unfollow"),
    path('post/<int:id>', views.post, name="post"),
    path('add_comment/<int:postid>', views.add_comment, name="add_comment"),
    path('like_post/<int:postid>', views.like_post, name="like_post"),
    path('unlike_post/<int:postid>', views.unlike_post, name="unlike_post"),
]

if settings.DEBUG:
    #connecting Media url to Media dir
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socialapp.urls'))
]

socialapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Post table
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=500)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

#Follow table
class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')

    #for having unique pairs
    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'

#Liked table
class Like(models.Model):
    likedBy = models.ForeignKey(User, on_delete=models.CASCADE)
    likedPost = models.ForeignKey(Post, on_delete=models.CASCADE)

    #again for having unique pairs
    class Meta:
        unique_together = ( 'likedBy', 'likedPost')

    def __str__(self):
        return f'{self.likedBy.username} liked {self.likedPost}'
    
#comment table
class Comment(models.Model):
    comment = models.CharField(max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user}: {self.comment}'

socialapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'desc', 'image']  # Specify the fields you want in the form

        # Optionally, you can customize widgets or labels here
        widgets = {
            'desc': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }
        labels = {
            'title': 'Post Title',
            'desc': 'Post Description',
            'image': 'Add Image',
        }

socialapp/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Post, Follow, Comment, Like
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import PostForm
from django.urls import reverse


# Create your views here.
def homepage(request):
    posts = Post.objects.all().order_by('-created_at')
    for post in posts:
        likes = Like.objects.filter(likedPost=post)
        post.likes = len(likes)
    context={
        'posts': posts
    }
    return render(request, 'homepage.html', context)

def profile(request):
    if request.user.is_authenticated:
        user = request.user
        posts = Post.objects.filter(user=user).order_by('-created_at')
        for post in posts:
            likes = Like.objects.filter(likedPost=post)
            post.likes = len(likes)
        followers = Follow.objects.filter(following=user)
        following = Follow.objects.filter(follower=user)

        form = PostForm()
        
        context={
            'user': user,
            'posts': posts,
            'form': form,
            'followers': followers,
            'following': following,
        }
        return render(request, 'profile.html', context)
    
    return redirect('/auth/login')

def create_post(request):
    if request.method == 'POST' and request.user.is_authenticated:
        print(request.FILES)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            #doing this bcoz i want the post instance before saving in db
            post = form.save(commit=False)
            #now i'll add user in my post instance
            post.user = request.user
            #and finally save the post instance in db
            post.save()
            return redirect('profile')
    
    return redirect('profile')

def delete_post(request, id):
    if request.user.is_authenticated:
        post = Post.objects.filter(id=id).first()
        
        if request.user == post.user:
            post.delete()
            return redirect('profile')
    
    return redirect('profile')

def showuser(request, id):
    if not request.user.is_authenticated:
        return redirect('/auth/login')
    user = User.objects.filter(id=id).first()
    if not user:
        return HttpResponse("user not found") 
    if user == request.user:
        return redirect('profile')
    posts = Post.objects.filter(user=user).order_by('-created_at')
    for post in posts:
        likes = Like.objects.filter(likedPost=post)
        post.likes = len(likes)
    followers = Follow.objects.filter(following=user)
    following = Follow.objects.filter(follower=user)
    doIFollow = Follow.objects.filter(follower=request.user, following=user).exists()

    context={
            'user': user,
            'posts': posts,
            'followers': followers,
            'following': following,
            'doIFollow': doIFollow,
        }
    return render(request, 'showuser.html', context)

def follow(request, id):
    if request.user.is_authenticated:
        userToFollow = User.objects.filter(id=id).first()
        if userToFollow:
            created = Follow.objects.create(follower=request.user, following=userToFollow)
            if created:
                # Generate the absolute URL using reverse
                url = reverse('showuser', kwargs={'id': id})
                return redirect(url)
           
    
    return redirect('profile')

def unfollow(request, id):
    if request.user.is_authenticated:
        userToUnFollow = User.objects.filter(id=id).first()
        if userToUnFollow:
            Follow.objects.filter(follower=request.user, following=userToUnFollow).delete()
            
            # Generate the absolute URL using reverse
            url = reverse('showuser', kwargs={'id': id})
            return redirect(url)
           
    
    return redirect('profile')

def post(request, id):
    post = Post.objects.filter(id=id).first()
    comments = Comment.objects.filter(post=post)
    likes = Like.objects.filter(likedPost=post)
    doILike = False
    try:
        doILike = likes.filter(likedBy=request.user)
    except(Exception):
        pass
    
    context={
        'post':post,
        'comments': comments,
        'likes': likes,
        'doILike': doILike,
    }
    
    return render(request, 'post.html', context)

def add_comment(request, postid):
    comm = request.POST.get('comment')
    post = Post.objects.get(id=postid)
    if request.user.is_authenticated:
        comment = Comment.objects.create(user=request.user, comment=comm, post=post)
        comment.save()
        url = reverse('post', kwargs={'id': postid})
        return redirect(url)


def like_post(request, postid):
    if not request.user.is_authenticated:
        return redirect("/auth/login")
    
    post = Post.objects.get(id=postid)
    try:
        liked = Like.objects.create(likedBy=request.user, likedPost=post)
        liked.save()
    except(Exception):
        #if user has already liked this post but illegaly hitting this url tryna hack the sys lmao
        pass
    finally:
        url = reverse('post', kwargs={'id': postid})
        return redirect(url)
    
def unlike_post(request, postid):
    if not request.user.is_authenticated:
        return redirect("/auth/login")
    
    post = Post.objects.get(id=postid)
    try:
        liked = Like.objects.get(likedBy=request.user, likedPost=post)
        liked.delete()
    except(Exception):
        pass
    finally:
        url = reverse('post', kwargs={'id': postid})
        return redirect(url)



#AUTHENTICATIONS FUNCTIONS
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/profile')
    else:
        form = UserCreationForm()
    
    return render(request, 'auth/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profile')  # Redirect to the homepage after successful login      
        
            #here all the else parts are to be written for better UX    
        
    else:
        form = AuthenticationForm()
    
    return render(request, 'auth/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')

socialapp/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">SocialApp</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile">Profile</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% comment %} All Posts {% endcomment %}
    <div class="container">
      <h1 class="my-5">Home Page</h1>
      <div class="d-flex flex-column gap-5 p-3">
        {% for post in posts %}
        <div class="card text-center">
          <div class="card-header">
            <a href="/showuser/{{ post.user.id }}">@{{post.user.username}}</a>
          </div>
          <div class="card-body">
            {% if post.image %}
            <div class="mb-3">
              <img src="{{ post.image.url }}" alt="user post image" class="img-fluid"/>
            </div>
            {% endif %}
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.desc}}</p>
            <div class="d-flex flex-column gap-2 justify-content-center align-items-center">
              <a href="{% url 'post' post.id %}" class="btn btn-primary">View</a>
              <h6 class="text-danger">&hearts; {{ post.likes }}</h6>
            </div>
          </div>
          <div class="card-footer text-body-secondary">{{post.created_at}}</div>
        </div>
        {% endfor %}
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

{% comment %} {% for post in posts %}
<div>
  <h6>By: @{{ post.user.username }}</h6>
  <h2>{{post.title}}</h2>
  <h4>{{post.desc}}</h4>
</div>
{% endfor %} {% endcomment %}

socialapp/templates/post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">SocialApp</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile">Profile</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% comment %} Post Page {% endcomment %}
    <div class="container">
      <div class="d-flex justify-content-between align-items-center my-5">
        <h1>{{ post.title }}</h1>
        <a class="px-3 py-2 text-decoration-none border rounded" href="{% url 'showuser' post.user.id %}">@{{ post.user }}</a>
      </div>

      {% if post.image %}
      <div class="mb-3 text-center">
        <img src="{{ post.image.url }}" alt="user post image" class="img-fluid"/>
      </div>
      {% endif %}

      <p>{{ post.desc }}</p>     


      {% comment %} Add Like && New Comment {% endcomment %}
      {% if not doILike %}
      <a href="{% url 'like_post' post.id %}" class="btn btn-danger"><h6>&hearts; {{ likes.count }}</h6></a>
      {% endif %}
      {% if doILike %}
      <a href="{% url 'unlike_post' post.id %}" class="btn btn-outline-danger"><h6>&hearts; {{ likes.count }}</h6></a>
      {% endif %}

      {% if request.user.is_authenticated %}
      <h2 class="text-center mt-5">Add Comment</h2>
      <form method="post" action="{% url 'add_comment' post.id %}" class="d-flex flex-column gap-5">
        {% csrf_token %}
        
        <!-- Comment Field -->
        <div class="form-group">
            <label for="id_comment">Comment</label>
            <textarea name="comment" id="id_comment" required minlength="2" class="form-control" rows="5"></textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
      {% endif %}


      {% comment %} Display Post Comments {% endcomment %}
      <h2 class="text-center mt-5">Comments({{ comments.count }})</h2>
      <ul>
      {% for comment in comments %}
        <li><a href="{% url 'showuser' comment.user.id %}" class="text-decoration-none">@{{ comment.user }}</a>: {{ comment.comment }}</li>
      {% endfor %}
      </ul>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

{% comment %} {% for post in posts %}
<div>
  <h6>By: @{{ post.user.username }}</h6>
  <h2>{{post.title}}</h2>
  <h4>{{post.desc}}</h4>
</div>
{% endfor %} {% endcomment %}

socialapp/templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">SocialApp</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile">Profile</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% comment %} Profile Page {% endcomment %}
    <div class="container">
      <div class="d-flex justify-content-between align-items-center my-5">
        <h1>Profile Page</h1>
        <a class="px-3 py-2 bg-danger text-white text-decoration-none border rounded" href="{% url 'logout' %}">Logout</a>
      </div>
      <h1>Welcome {{ user.username }}</h1>
      <div class="d-flex justify-content-evenly text-center my-5">
        {% comment %} Followers {% endcomment %}
        <div class="d-flex flex-column gap-2">
            <h2>{{ followers.count }} Followers</h2>
            <ul>
            {% for record in followers %}
              <li><a href="/showuser/{{ record.follower.id }}">@{{record.follower}}</a></li>  
            {% endfor %}
            </ul>  
        </div>
        {% comment %} Following {% endcomment %}
        

        <div class="d-flex flex-column gap-2">
          <h2>{{ following.count }} Following</h2>
          <ul>
          {% for record in following %}
            <li><a href="/showuser/{{ record.following.id }}">@{{record.following}}</a></li>  
          {% endfor %}
          </ul>  
      </div>
      </div>


      {% comment %} Add New Post {% endcomment %}
      <h2 class="text-center mt-5">Add New Post</h2>
      <form method="post" action="{% url 'create_post' %}" class="d-flex flex-column gap-5" enctype="multipart/form-data">
        {% csrf_token %}
        
        <!-- Title Field -->
        <div class="form-group">
            <label for="id_title">Post Title</label>
            <input type="text" name="title" required minlength="2" id="id_title" class="form-control" value="{{ form.title.value|default_if_none:'' }}" />
        </div>
        
        <!-- Description Field -->
        <div class="form-group">
            <label for="id_desc">Post Description</label>
            <textarea name="desc" id="id_desc" required minlength="2" class="form-control" rows="5">{{ form.desc.value|default_if_none:'' }}</textarea>
        </div>

        <!-- Image Field -->
        <div class="form-group">
          <label for="id_image">Add Image</label>
          <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
      </div>
        
        <button type="submit" class="btn btn-primary">Add</button>
    </form>


      {% comment %} Display User Posts {% endcomment %}
      <h2 class="text-center mt-5">Your Posts({{ posts.count }})</h2>
      <div class="row p-3">
        {% for post in posts %}
        <div class="card text-center col-0 col-lg-3 mx-lg-5 mb-5">
          <div class="card-header">@{{post.user.username}}</div>
          <div class="card-body">
            {% if post.image %}
            <div class="mb-3">
              <img src="{{ post.image.url }}" alt="user post image" class="img-fluid"/>
            </div>
            {% endif %}
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.desc}}</p>
            <div class="d-flex gap-2 justify-content-center">
              <a href="{% url 'post' post.id %}" class="btn btn-primary">View</a>
              <a href="{% url 'delete_post' post.id %}" class="btn btn-danger">Delete</a>
            </div>
            <h6 class="text-danger mt-4">&hearts; {{ post.likes }}</h6>
          </div>
          <div class="card-footer text-body-secondary">{{post.created_at}}</div>
        </div>
        {% endfor %}
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

{% comment %} {% for post in posts %}
<div>
  <h6>By: @{{ post.user.username }}</h6>
  <h2>{{post.title}}</h2>
  <h4>{{post.desc}}</h4>
</div>
{% endfor %} {% endcomment %}

socialapp/templates/showuser.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">SocialApp</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile">Profile</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% comment %} Profile Page {% endcomment %}
    <div class="container">
      <div class="d-flex justify-content-between align-items-center my-5">
        <h1>Profile Page</h1>
        {% if doIFollow %}
        <a class="px-3 py-2 bg-danger text-white text-decoration-none border rounded" href="{% url 'unfollow' user.id %}">Unfollow</a>
        {% endif %}
        {% if not doIFollow %}
        <a class="px-3 py-2 bg-primary text-white text-decoration-none border rounded" href="{% url 'follow' user.id %}">Follow</a>
        {% endif %}
      </div>
      <h1>{{ user.username }}</h1>
      <div class="d-flex justify-content-evenly text-center my-5">
        {% comment %} Followers {% endcomment %}
        <div class="d-flex flex-column gap-2">
            <h2>{{ followers.count }} Followers</h2>
            <ul>
            {% for record in followers %}
              <li><a href="/showuser/{{ record.follower.id }}">@{{record.follower}}</a></li>  
            {% endfor %}
            </ul>  
        </div>
        {% comment %} Following {% endcomment %}
        

        <div class="d-flex flex-column gap-2">
          <h2>{{ following.count }} Following</h2>
          <ul>
          {% for record in following %}
            <li><a href="/showuser/{{ record.following.id }}">@{{record.following}}</a></li>  
          {% endfor %}
          </ul>  
      </div>
      </div>

      {% comment %} Display User Posts {% endcomment %}
      <h2 class="text-center mt-5">{{ user.username }}'s Posts({{ posts.count }})</h2>
      <div class="row p-3">
        {% for post in posts %}
        <div class="card text-center col-0 col-lg-3 mx-lg-5 mb-5">
          <div class="card-header">@{{post.user.username}}</div>
          <div class="card-body">
            {% if post.image %}
            <div class="mb-3">
              <img src="{{ post.image.url }}" alt="user post image" class="img-fluid"/>
            </div>
            {% endif %}
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.desc}}</p>
            <div class="d-flex flex-column gap-2 justify-content-center align-items-center">
              <a href="{% url 'post' post.id %}" class="btn btn-primary">View</a>
              <h6 class="text-danger">&hearts; {{ post.likes }}</h6>
            </div>
          </div>
          <div class="card-footer text-body-secondary">{{post.created_at}}</div>
        </div>
        {% endfor %}
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>